### ISSUE TITLE
Filter for Fighters and Drones switched

### ISSUE THREAD

**Issue by Blaumeise03** [sweet-org/sweet#17]
Drones are only selectable inside of captials, while fighters can only be selected for subcaps. It does also affect the old version, so it seems like another problem with the latest patch data.
Also the VAS don't display launch tubes for lightweight fighters anymore and the special rigs to adjust the type of fighter can't be selected anymore.

**Comment by Blaumeise03** [comment]
The market groups inside `lib/bloc/item_repository_bloc/market_group_filters.dart` are outdated, the ids for around 140 market groups got changed in one of the patches. That causes Nullpointer exceptions because the app tries to access non-existing market groups.

**Comment by Blaumeise03** [comment]
I have updated the attribute ids, fitting does now work, but for caps it is possible to also fit the wrong type of fighters. More specifically, carriers can fit lightweight ships. Requires probably an additional check because lightweight ships do not have a canFit attribute id as far as I can tell.

**Comment by IsaacOstlund** [comment]
VAC LWs still not working for me. If im in Vassago, for example, i cannot select frigs or dessie slots. Pushing the Fill All or any of the "empty" slots does nothing.

**Comment by Blaumeise03** [comment]
Yeah sorry, the update isn't merged into the main branch yet. Have just pushed it to my fork (in case someone already want to use it). Once everything is fixed, it will be uploaded.
