### ISSUE TITLE
App GUI Firepower section breaks when fitting Doomsday Weapon

### ISSUE THREAD

**Issue by xpycmuk** [sweet-org/sweet#18]
When fitting Doomsday Weapon on Dreadnought, Firepower section breaks.

 Without Doomsday Weapon 
![image](https://github.com/user-attachments/assets/9e4cd7b8-fc4b-4c1a-9b2a-3ade333e06f2)

 With Doomsday Weapon 
![image](https://github.com/user-attachments/assets/146ceedb-bf2c-4357-ac5c-2092a01e2e40)

Tested on Desktop and Android

SWEET App
![image](https://github.com/user-attachments/assets/7c0addcd-6794-42ac-86af-85046c6fbff8)

**Comment by Blaumeise03** [comment]
That bug is caused by a nullpointer exception inside the fitting_simulator. Doomsday weapons don't have an activation time attribute.
