### ISSUE TITLE
VACs cannot fit anything in their "lightweight" slots

### ISSUE THREAD

**Issue by IsaacOstlund** [sweet-org/sweet#19]
Not sure if this is related to the other drone/fighter problem, but in any VAC you cannot press an empty slot or the "fill all" button for the frigate/destroyers. trying to click those buttons does nothing.

**Comment by Blaumeise03** [comment]
Yes, thats also because of the market groups issue and already fixed in the commit I pushed for the other issue.

Duplicate of #17

**Comment by Blaumeise03** [comment]
Duplicate of #17
