### ISSUE TITLE
Higgs Anchor rigs can be integrated

### ISSUE THREAD

**Issue by SilkyPantsDan** [sweet-org/sweet#5]
This is due to the 'Cannot be integrated' (193) attribute not being added and checked when filtering available rigs

![image](https://github.com/sweet-org/sweet/assets/738172/fb41548c-fe37-44c2-b9d0-448d568606c1)

**Comment by Blaumeise03** [comment]
I have started to look into it. My current (working) solution is an hardcoded blacklist of mainCalCodes inside the ship_fitting_bloc/bloc.dart. The blacklist gets used to filter out the item selection menu (so it won't be possible to put a blacklisted rig into an integrated rig in the first place. But there are two cases:

The easy case is, if there is already a rig inside the integrated rig. In this case only the compatible rigs gets displayed and it is possible to filter out the blacklisted rigs directly inside bloc.dart.

The second case is more complicated. If there is no rig inside the integrated rig, all market groups get displayed and every market group contains the rigs itself. To filter out the items, the blacklist propagates through the `OpenRigIntegratorDrawer` event into the `ShipFittingContextDrawer` widget recursively into all `MarketGroupTile` widgets. In the `build` function of the `MarketGroupTile` the blacklist gets used to apply the filter on the item list.

![grafik](https://github.com/sweet-org/sweet/assets/43181741/f2f85b2e-3a6d-4c29-a9fa-de2a38b49c74)

This does work, but is not a very nice solution as it requires an hardcoded blacklist. I don't know how exactly the item attribute loading works (so wether all attributes for all items get caches somewhere or get loaded on-demand from the database). As far as I can tell, we don't have access to an items attributes inside `ship_fitting_bloc/bloc.dart`. So it would probably a bad idea to load all attributes every time a user opens the item selection list to filter out the rigs with the `Cannot be integrated` attribute.

At the moment the higgs anchors are the only rigs that can't be integrated:
![grafik](https://github.com/sweet-org/sweet/assets/43181741/18e9fc3a-405a-4931-bca7-6ad97aef260e)

A solution would probably to create the blacklist one time during startup of the app, the perfomance impact using a single sql command should not be to high, as there are only few items that have this attribute. But I don't know yet how to use the database properly.

**Comment by SilkyPantsDan** [comment]
Just thinking about this - I think we could do a bit of a simple add here to implement as you have suggested.
- Create new DB function in `lib/repository/item_repository_db_functions.dart` to get all the item IDs with a given attribute ID
- Call this new function either as part of `[processMarketGroups](https://github.com/sweet-org/sweet/blob/main/lib/repository/item_repository.dart#L218) or create a new function specifically for this (which might be the better option thinking about it)
- Cache off any IDs that are returned with an attribute value of  `1`

The query itself wouldn't need to be any more than this:
```SELECT itemId, value
FROM item_attributes
WHERE attributeId = 193```

And we can either add `AND value <> 0.0` or do the final check elsewhere - or even skip it altogether and just grab the IDs and run. I guess it's a question of whether NE ever update this to have anything other than 1.0

Once we have these IDs cached, we can add them to the filter method in `mapShowRigIntegrationMenu`

Something like:
```    final filteredGroup = MarketGroup.clone(
      group,
      group.children.where((g) => g.id != parentMarketGroupId).toList() && !_itemRepository.excludedFusionRigs.contains(g.id),
      null,
    );```
